name: Build and test NPOI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build-and-test:
    strategy:
          matrix:
            dotnet: [ '2.0.x', '2.1.x', '5.0.x', '7.0.x' ]
    runs-on: ubuntu-latest
    name: Build and Text with dotnet ${{ matrix.dotnet }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Create temporary global.json
      run: echo '{"sdk":{"version": "${{ steps.stepid.outputs.dotnet-version }}"}}' > ./global.json
    - name: Restore dependencies
      run: dotnet restore solution/NPOI.Core.Test.sln
    - name: Build
      run: dotnet build solution/NPOI.Core.Test.sln --no-restore
    - name: Test
      run: dotnet test solution/NPOI.Core.Test.sln --no-build --verbosity normal
